version: "3"
services:
    dropbox:
      restart: always
      build:
        context: ./image

      volumes:
        - "/home/${USER_NAME}/DropboxDocker:/dbox/Dropbox"

      environment:
        - DBOX_UID=
        - DBOX_GID=
        - DBOX_SKIP_UPDATE=
